[phases.setup]
# İsteğe bağlı ama netlik için: Go 1.22 kullan
nixPkgs = ["go_1_22"]

[phases.install]
# Sadece modülleri indir, tidy burada ÇALIŞMASIN
cmds = ["go mod download"]

[phases.build]
# En son copy’den sonra çalışacak: önce tidy, sonra build
cmds = ["go mod tidy", "go build -o out"]

[start]
cmd = "./out"
