name: go mod tidy & push
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Bu adım dependency'yi kesin ekler (go.mod'da yoksa ekler)
      - run: go get github.com/xhit/go-simple-mail/v2@v2.16.0

      # go.sum üret / güncelle
      - run: go mod tidy

      # değişiklik varsa commit et
      - name: Commit go.sum
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add go.mod go.sum
            git commit -m "chore: add/update go.sum via CI"
            git push
          fi

